# Generated by Django 4.1 on 2024-03-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_category_movie_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
