# Generated by Django 4.1 on 2024-03-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('title',), 'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
    ]
