# Generated by Django 4.1 on 2024-03-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_movie_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='added_by',
        ),
    ]
